# Helper method that provides the path to a fixtures dir where
# files generated by the test are housed
module FixturesHelper
  def fixtures_dir
    File.join(
        File.dirname(__FILE__), 'fixtures')
  end
end
